/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.awt.event.KeyEvent;
import java.awt.Dialog;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import Konektor.Koneksi;
import javax.swing.JFrame;
/**
 *
 * @author asus
 */
public class Mahasiswa extends javax.swing.JFrame {
    public final Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    
    private void aktif(){
        NIM_TF.setEnabled(true);
        Nama_TF.setEnabled(true);
        Kelas_TF.setEnabled(true);
        Jurusan_TF.setEnabled(true);
        SMT_Box.setEnabled(true);
    }
    
    protected void kosong(){
        NIM_TF.setText(null);
        Nama_TF.setText(null);
        Kelas_TF.setText(null);
        Jurusan_TF.setText(null);
        SMT_Box.setSelectedItem("Select Semester");
    }
    
    public void lebarKolom() {
        TableColumn kolom;
        Mhs_TB.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kolom = Mhs_TB.getColumnModel().getColumn(0);
        kolom.setPreferredWidth(150);
        kolom = Mhs_TB.getColumnModel().getColumn(1);
        kolom.setPreferredWidth(150);
        kolom = Mhs_TB.getColumnModel().getColumn(2);
        kolom.setPreferredWidth(50);
        kolom = Mhs_TB.getColumnModel().getColumn(3);
        kolom.setPreferredWidth(150);
        kolom = Mhs_TB.getColumnModel().getColumn(4);
        kolom.setPreferredWidth(150);
    }
    
    public void dataTable(){
        Object [] Baris = {"NIM","NAMA LENGKAP","KELAS","JURUSAN","SEMESTER"};
        tabmode = new DefaultTableModel (null, Baris);
        Mhs_TB.setModel(tabmode);
        String sql = "select*from tb_mahasiswa order by nim asc";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String NIM = hasil.getString("nim");
                String Nama = hasil.getString("nama");
                String Kelas = hasil.getString("kelas");
                String Jurusan = hasil.getString("jurusan");
                String Semester = hasil.getString("semester");
                String [] data = {NIM,Nama,Kelas,Jurusan,Semester};
                tabmode.addRow(data);
            }
           }catch (Exception e){
            
        }
        
    }
    
    public void pencarian (String sql){
        Object [] Baris = {"NIM","NAMA LENGKAP","KELAS","JURUSAN","SEMESTER"};
        tabmode = new DefaultTableModel (null,Baris);
        Mhs_TB.setModel(tabmode);
        int brs = Mhs_TB.getRowCount();
        for (int i = 0;1<brs;i++){
            tabmode.removeRow(i);
        }
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String NIM = hasil.getString("nim");
                String Nama = hasil.getString("nama");
                String Kelas = hasil.getString("kelas");
                String Jurusan = hasil.getString("jurusan");
                String Semester = hasil.getString("semester");
                String [] data = {NIM,Nama,Kelas,Jurusan,Semester};
                tabmode.addRow(data);
               lebarKolom();
            }
            
        } catch (Exception e){
            
        }
    }


    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        aktif();
        dataTable();
        lebarKolom();
        NIM_TF.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UbahCh_D = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NIMCh_TF = new javax.swing.JTextField();
        NamaCh_TF = new javax.swing.JTextField();
        KelasCh_TF = new javax.swing.JTextField();
        JurusanCh_TF = new javax.swing.JTextField();
        SMTCh_Box = new javax.swing.JComboBox<>();
        CancelCh_Btn = new javax.swing.JButton();
        SimpanCh_Btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NIM_TF = new javax.swing.JTextField();
        Nama_TF = new javax.swing.JTextField();
        Kelas_TF = new javax.swing.JTextField();
        SMT_Box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mhs_TB = new javax.swing.JTable();
        Search_TF = new javax.swing.JTextField();
        Search_Btn = new javax.swing.JButton();
        Tambah_Btn = new javax.swing.JButton();
        Ubah_Btn = new javax.swing.JButton();
        Hapus_Btn = new javax.swing.JButton();
        Bersih_Btn = new javax.swing.JButton();
        Cancel_Btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jurusan_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        UbahCh_D.setMinimumSize(new java.awt.Dimension(476, 360));

        jPanel2.setMinimumSize(new java.awt.Dimension(476, 360));

        jLabel13.setText("NIM");

        jLabel9.setText("Nama");

        jLabel10.setText("Kelas");

        jLabel11.setText("Semester");

        jLabel12.setText("Program Studi");

        NIMCh_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NIMCh_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NIMCh_TFKeyPressed(evt);
            }
        });

        NamaCh_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaCh_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaCh_TFKeyPressed(evt);
            }
        });

        KelasCh_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KelasCh_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KelasCh_TFKeyPressed(evt);
            }
        });

        JurusanCh_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SMTCh_Box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SMTCh_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Select Semester ----", "1 (Ganjil)", "2 (Genap)", "3 (Ganjil)", "4 (Genap)", "5 (Ganjil)", "6 (Genap)", "7 (Ganjil)", "8 (Genap)", " " }));

        CancelCh_Btn.setText("Cancel");
        CancelCh_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCh_BtnActionPerformed(evt);
            }
        });

        SimpanCh_Btn.setText("Simpan");
        SimpanCh_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanCh_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NIMCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(107, 107, 107)
                                .addComponent(NamaCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SMTCh_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(KelasCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JurusanCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(SimpanCh_Btn)
                .addGap(46, 46, 46)
                .addComponent(CancelCh_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NIMCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(NamaCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(KelasCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JurusanCh_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SMTCh_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanCh_Btn)
                    .addComponent(CancelCh_Btn))
                .addGap(191, 191, 191))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UbahCh_DLayout = new javax.swing.GroupLayout(UbahCh_D.getContentPane());
        UbahCh_D.getContentPane().setLayout(UbahCh_DLayout);
        UbahCh_DLayout.setHorizontalGroup(
            UbahCh_DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UbahCh_DLayout.setVerticalGroup(
            UbahCh_DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahCh_DLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        NIM_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NIM_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NIM_TFKeyPressed(evt);
            }
        });
        jPanel1.add(NIM_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 360, -1));

        Nama_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nama_TFKeyPressed(evt);
            }
        });
        jPanel1.add(Nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 360, -1));

        Kelas_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kelas_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Kelas_TFKeyPressed(evt);
            }
        });
        jPanel1.add(Kelas_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 360, -1));

        SMT_Box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SMT_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester ", "1 (Ganjil)", "2 (Genap)", "3 (Ganjil)", "4 (Genap)", "5 (Ganjil)", "6 (Genap)", "7 (Ganjil)", "8 (Genap)" }));
        SMT_Box.setPreferredSize(new java.awt.Dimension(7, 28));
        jPanel1.add(SMT_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 360, -1));

        Mhs_TB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mhs_TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Mhs_TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mhs_TBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Mhs_TB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 237, 530, 410));

        Search_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TFActionPerformed(evt);
            }
        });
        Search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Search_TFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Search_TFKeyTyped(evt);
            }
        });
        jPanel1.add(Search_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 400, 30));

        Search_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/flat-color-icons_search.png"))); // NOI18N
        Search_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Search_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 190, 50, 30));

        Tambah_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tambah_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/ion_add-circle.png"))); // NOI18N
        Tambah_Btn.setText("Tambah");
        Tambah_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Tambah_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));

        Ubah_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ubah_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/entypo_edit.png"))); // NOI18N
        Ubah_Btn.setText("Ubah");
        Ubah_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ubah_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Ubah_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 110, 30));

        Hapus_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hapus_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/clarity_trash-solid.png"))); // NOI18N
        Hapus_Btn.setText("Hapus");
        Hapus_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 110, -1));

        Bersih_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bersih_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/bx_bxs-eraser.png"))); // NOI18N
        Bersih_Btn.setText("Bersih");
        Bersih_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bersih_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Bersih_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 110, 30));

        Cancel_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cancel_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/topcoat_cancel (1).png"))); // NOI18N
        Cancel_Btn.setText("Cancel");
        Cancel_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cari");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Program Studi");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        Jurusan_TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jurusan_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jurusan_TFKeyPressed(evt);
            }
        });
        jPanel1.add(Jurusan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 360, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/Desktop - 5 (1)_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1372, 725));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tambah_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_BtnActionPerformed
        // TODO add your handling code here:
        if (NIM_TF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NIM Tidak Boleh Kosong");
        } else if (Nama_TF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NAMA Tidak Boleh Kosong");
        } else if (Kelas_TF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"KELAS Tidak Boleh Kosong");
        } else if (Jurusan_TF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PROGRAM STUDI Tidak Boleh Kosong");
        } else if (SMT_Box.getSelectedItem().equals("Select Semester")){
            JOptionPane.showMessageDialog(null, "SEMESTER Harus Dipilih");
        } else {
            String sql = "insert into tb_mahasiswa values (?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, NIM_TF.getText());
                stat.setString(2, Nama_TF.getText());
                stat.setString(3, Kelas_TF.getText());
                stat.setString(4, Jurusan_TF.getText());
                stat.setString(5, (String)SMT_Box.getSelectedItem());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                kosong();
                dataTable();
                lebarKolom();
                NIM_TF.requestFocus();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e);
            }
        }
    }//GEN-LAST:event_Tambah_BtnActionPerformed

    private void NIM_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIM_TFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Nama_TF.requestFocus();
        }
    }//GEN-LAST:event_NIM_TFKeyPressed

    private void Search_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_TFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_TFKeyPressed

    private void Nama_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama_TFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Kelas_TF.requestFocus();
        }
    }//GEN-LAST:event_Nama_TFKeyPressed

    private void Kelas_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Kelas_TFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Jurusan_TF.requestFocus();
        }
    }//GEN-LAST:event_Kelas_TFKeyPressed

    private void Jurusan_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jurusan_TFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            NIM_TF.requestFocus();
        }
    }//GEN-LAST:event_Jurusan_TFKeyPressed

    private void Bersih_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bersih_BtnActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_Bersih_BtnActionPerformed

    private void Hapus_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus_BtnActionPerformed
        // TODO add your handling code here:
        int Check = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin" + " Menghapus Data ", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if(Check == 0){
            String sql = "delete from tb_mahasiswa where nim='"+ NIM_TF.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                dataTable();
                lebarKolom();
             
                
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e);
            }
        }
    }//GEN-LAST:event_Hapus_BtnActionPerformed

    private void Cancel_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_BtnActionPerformed
        // TODO add your handling code here:
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
        MA.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_Cancel_BtnActionPerformed

    private void Ubah_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ubah_BtnActionPerformed
        // TODO add your handling code here:
        UbahCh_D.setLocationRelativeTo(this);
        UbahCh_D.setVisible(true);
    }//GEN-LAST:event_Ubah_BtnActionPerformed

    private void Mhs_TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mhs_TBMouseClicked
        // TODO add your handling code here:
        int bar = Mhs_TB.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        
        
        NIM_TF.setText(a);
        NIMCh_TF.setText(a);
        Nama_TF.setText(b);
        NamaCh_TF.setText(b);
        Kelas_TF.setText(c);
        KelasCh_TF.setText(c);
        Jurusan_TF.setText(d);
        JurusanCh_TF.setText(d);
        SMT_Box.setSelectedItem(e);
        SMTCh_Box.setSelectedItem(e);
    }//GEN-LAST:event_Mhs_TBMouseClicked

    private void NIMCh_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIMCh_TFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMCh_TFKeyPressed

    private void NamaCh_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaCh_TFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaCh_TFKeyPressed

    private void KelasCh_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KelasCh_TFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasCh_TFKeyPressed

    private void CancelCh_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCh_BtnActionPerformed
        // TODO add your handling code here:
        UbahCh_D.setVisible(false);
    }//GEN-LAST:event_CancelCh_BtnActionPerformed

    private void SimpanCh_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanCh_BtnActionPerformed
        // TODO add your handling code here:
         String sql = "update tb_mahasiswa set nim='"+ NIMCh_TF.getText()+"',nama='"+NamaCh_TF.getText()+"',kelas='"+KelasCh_TF.getText()+"',jurusan='"+ JurusanCh_TF.getText()+ "',semester='"+SMTCh_Box.getSelectedItem()+"' where nim='" + NIM_TF.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            dataTable();
            lebarKolom();

            NIM_TF.requestFocus();
            UbahCh_D.dispose();

        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+ e);
        }
    }//GEN-LAST:event_SimpanCh_BtnActionPerformed

    private void Search_TFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_TFKeyTyped
        // TODO add your handling code here:
    String sqlPencarian = "select * from tb_mahasiswa where nim like '%"+ Search_TF.getText()+"%' or " 
                +"nama like '%" + Search_TF.getText()+ "%' or " + "semester like '%" + Search_TF.getText()+ "%'";
        pencarian(sqlPencarian);
        lebarKolom();
    }//GEN-LAST:event_Search_TFKeyTyped

    private void Search_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BtnActionPerformed
        // TODO add your handling code here:
       String sqlPencarian = "select * from tb_mahasiswa where nim like '%"+ Search_TF.getText()+"%' or " 
                +"nama like '%" + Search_TF.getText()+ "%' or " + "semester like '%" + Search_TF.getText()+ "%'";
        pencarian(sqlPencarian);
        lebarKolom();
    }//GEN-LAST:event_Search_BtnActionPerformed

    private void Search_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersih_Btn;
    private javax.swing.JButton CancelCh_Btn;
    private javax.swing.JButton Cancel_Btn;
    private javax.swing.JButton Hapus_Btn;
    private javax.swing.JTextField JurusanCh_TF;
    private javax.swing.JTextField Jurusan_TF;
    private javax.swing.JTextField KelasCh_TF;
    private javax.swing.JTextField Kelas_TF;
    private javax.swing.JTable Mhs_TB;
    private javax.swing.JTextField NIMCh_TF;
    private javax.swing.JTextField NIM_TF;
    private javax.swing.JTextField NamaCh_TF;
    private javax.swing.JTextField Nama_TF;
    private javax.swing.JComboBox<String> SMTCh_Box;
    private javax.swing.JComboBox<String> SMT_Box;
    private javax.swing.JButton Search_Btn;
    private javax.swing.JTextField Search_TF;
    private javax.swing.JButton SimpanCh_Btn;
    private javax.swing.JButton Tambah_Btn;
    private javax.swing.JDialog UbahCh_D;
    private javax.swing.JButton Ubah_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
