/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Konektor.Koneksi;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class MenuAdmin extends javax.swing.JFrame {
    private Connection conn = new Koneksi().connect();

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputMhs_Btn = new javax.swing.JButton();
        Kembali_Btn = new javax.swing.JButton();
        InputMkl_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputMhs_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InputMhs_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/input_data.png"))); // NOI18N
        InputMhs_Btn.setText("Input Data Mahasiswa ");
        InputMhs_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputMhs_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(InputMhs_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 250, 60));

        Kembali_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kembali_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/Back16px.png"))); // NOI18N
        Kembali_Btn.setText("Kembali");
        Kembali_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kembali_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Kembali_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 250, 60));

        InputMkl_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InputMkl_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/input_matkul.png"))); // NOI18N
        InputMkl_Btn.setText("Input Mata Kuliah");
        InputMkl_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputMkl_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(InputMkl_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/Desktop.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1372, 725));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputMhs_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputMhs_BtnActionPerformed
        // TODO add your handling code here:
        Mahasiswa Mhs = new Mahasiswa();
        Mhs.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Mhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InputMhs_BtnActionPerformed

    private void Kembali_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kembali_BtnActionPerformed
        // TODO add your handling code here:
         MenuUtama MU = new MenuUtama();
        MU.setExtendedState(MAXIMIZED_BOTH);
        MU.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Kembali_BtnActionPerformed

    private void InputMkl_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputMkl_BtnActionPerformed
        // TODO add your handling code here:
       Admin A = new Admin();
        A.setExtendedState(JFrame.MAXIMIZED_BOTH);
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InputMkl_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InputMhs_Btn;
    private javax.swing.JButton InputMkl_Btn;
    private javax.swing.JButton Kembali_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
