/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Konektor.Koneksi;
import javax.swing.JFrame;
/**
 * @author Kelompok 3
 * -Mar'atus Sholihah
 * -Sallma Diana Putri
 * -Azka Septia Rahman
 * -Indah Nurhayati
 * -Lhutfia Ichsan
 */

public class MenuUtama extends javax.swing.JFrame {
private Connection conn = new Koneksi().connect();
    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Mhs_Btn = new javax.swing.JButton();
        AdminMenu_Btn = new javax.swing.JButton();
        LogOut_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mhs_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Mhs_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/flat-color-icons_manager.png"))); // NOI18N
        Mhs_Btn.setText("MAHASISWA");
        Mhs_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mhs_BtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Mhs_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, -1, 60));

        AdminMenu_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdminMenu_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/flat-ui_shirt.png"))); // NOI18N
        AdminMenu_Btn.setText("ADMIN");
        AdminMenu_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminMenu_BtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(AdminMenu_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 180, 60));

        LogOut_Btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogOut_Btn.setText("Log Out");
        LogOut_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_BtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(LogOut_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambardanIcon/Desktop - 7.png"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jLabel2.setText("jLabel2");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminMenu_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminMenu_BtnActionPerformed
        // TODO add your handling code here:
        MenuAdmin MA = new MenuAdmin();
        MA.setExtendedState(JFrame.MAXIMIZED_BOTH);
        MA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminMenu_BtnActionPerformed

    private void Mhs_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mhs_BtnActionPerformed
        // TODO add your handling code here:
        Ambil_KRS IKRS = new Ambil_KRS();
        IKRS.setExtendedState(JFrame.MAXIMIZED_BOTH);
        IKRS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Mhs_BtnActionPerformed

    private void LogOut_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_BtnActionPerformed
      int logout = JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Keluar ?");
       if(logout == JOptionPane.YES_OPTION){
          loginForm LF = new loginForm();
          LF.setExtendedState(JFrame.MAXIMIZED_BOTH);
          LF.setVisible(true);
          this.dispose();
       }
           
    }//GEN-LAST:event_LogOut_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminMenu_Btn;
    private javax.swing.JButton LogOut_Btn;
    private javax.swing.JButton Mhs_Btn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
